### ISSUE TITLE
License(s) per datasets seems incorrect

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-knowledge-graph#54]
Issue https://github.com/netwerk-digitaal-erfgoed/dataset-knowledge-graph/issues/25 brought the analysis of used licenses. When I look at the licenses per dataset via [query](https://triplestore.netwerkdigitaalerfgoed.nl/sparql?name=&infer=true&sameAs=true&query=PREFIX%20dcterms%3A%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX%20void%3A%20%3Chttp%3A%2F%2Frdfs.org%2Fns%2Fvoid%23%3E%0A%0ASELECT%20%3Fdataset%20%3Flicense%20%20%7B%0A%20%20%3Fdataset%20a%20void%3ADataset%20%3B%0A%20%20%09void%3Asubset%20%5B%0A%20%20%20%20%20%20dcterms%3Alicense%20%3Flicense%0A%20%20%20%20%5D%20%20%0A%7D) on the dataset-knowledge-graph, I see several datasets have multiple licenses, which incorrect, for example:

https://studiezaal.nijmegen.nl/AtlantisPubliek/data/dataset/LOD+Beelddocumenten
- http://creativecommons.org/publicdomain/mark/1.0/ 
- http://rightsstatements.org/vocab/InC/1.0/
- http://creativecommons.org/publicdomain/zero/1.0/
- http://creativecommons.org/licenses/by-sa/4.0/

And I wonder about https://studiezaal.nijmegen.nl/AtlantisPubliek/data/dataset/Catalog. Although a Catalog does have a license (http://creativecommons.org/publicdomain/zero/1.0/ in this example), I wonder if we should count this as a Dataset?

**Comment by ddeboer** [comment]
@coret As we discussed today (and the readme says), these are:

> Licenses that apply to resources in the dataset.

So not to the dataset as whole, but to individual objects within the dataset. Do the results make more sense that way? If not, please let me know!

**Comment by coret** [comment]
Yes, I've checked the Gouda Timemachine KG and there appear multiple CC licenses (occuring within the datasetdescriptions which are part of this KG).

I do see that the query mentioned does produce significantly less results today than 3 days ago (Gouda Timemachine isn't part of the resultset, nor is Nijmegen).
